spring:
  application:
    name: BK-Back
  profiles:
    active: native

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

auth:
  google:
    client_id: "512265054010-31avv85pu1ufi1jbrd9vu3s5kj1006pa.apps.googleusercontent.com"
    client_secret: "DIybvRNaUF9muBoixFg_2zGP"
  local:
    token:
      secret: asdf